import Link from "next/link";
import Showcase from "../showcase/page";

const FirstSection = () => {
  return (
    <section className="md:pb-20 pb-10 bg-gradient-to-r from gray-00 to-gray-200 space-y-10">
      <div className="container mx-auto text-center">
        <div
          className="bg-orange-100 rounded-2xl mb-5 text-md uppercase tracking-wider font-bold text-orange-500
         inline-block px-4 py-1"
        >
          Transform your online presence with just a click.
        </div>
        <div
          className="text-7xl flex justify-center font-bold md:px-52 pb-10
        text-gradient
        bg-gradient-to-r
        from-orange-700
        to-red-300
        bg-clip-text
        text-transparent"
        >
          Professional AI Headshots in minutes.
        </div>
        <p
          className="text-2xl md:text-2xl md-10 md:px-44
        bg-gradient-to-r
        from-black
        to-gray-400
        bg-clip-text
        text-transparent
        font-bold"
        >
          Elevate your online presence with HD headshots generated by our AI.
          Ideal for social profiles, resumes, and professional portfolios.
        </p>
        <div className="flex gap-4 justify-center pt-10">
          <Link href="/login">
            <button
              className="bg-orange-700 hover:bg-orange-800 font-bold text-white px-6 py-2 rounded-md text-lg 
          transition transform motion-reduce:transition-none motion-reduce:hover:transform-none"
            >
              Get Your Headshots
            </button>
          </Link>
        </div>
        <div className="pt-10">
          <Showcase />
        </div>
      </div>
    </section>
  );
};

export default FirstSection;