import Link from "next/link";
import Showcase from "../showcase/page";
import { FaPaintBrush } from "react-icons/fa";

const FirstSection = () => {
  return (
    <section className="md:pb-20 pb-5 bg-gradient-to-r from-gray-00 to-gray-200 space-y-10 relative">
      <div className="container mx-auto text-center">
        {/* First Div with Arrow */}
        <div className="relative inline-block">
          <div className="bg-orange-100 rounded-lg mb-5 text-md uppercase tracking-wider font-bold text-orange-500 inline-block px-4 py-2 relative z-10">
            Transform your online presence with just a click.
          </div>
          {/* Twisted Arrow */}
          <div className="absolute w-10 h-10 -top-10 right-0 transform translate-x-[100%] translate-y-[10%]">
            <svg
              fill="rgb(249 115 22)"
              height="50px"
              width="50px"
              version="1.1"
              id="Layer_1"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 302.816 302.816"
              xmlLang="preserve"
              stroke="rgb(249 115 22)"
            >
              <g id="SVGRepo_bgCarrier" strokeWidth="0"></g>
              <g
                id="SVGRepo_tracerCarrier"
                strokeLinecap="round"
                strokeLinejoin="round"
              ></g>
              <g id="SVGRepo_iconCarrier">
                <path
                  id="XMLID_6_"
                  d="M298.423,152.996c-5.857-5.858-15.354-5.858-21.213,0l-35.137,35.136 c-5.871-59.78-50.15-111.403-112.001-123.706c-45.526-9.055-92.479,5.005-125.596,37.612c-5.903,5.813-5.977,15.31-0.165,21.213 c5.813,5.903,15.31,5.977,21.212,0.164c26.029-25.628,62.923-36.679,98.695-29.565c48.865,9.72,83.772,50.677,88.07,97.978 l-38.835-38.835c-5.857-5.857-15.355-5.858-21.213,0.001c-5.858,5.858-5.858,15.355,0,21.213l62.485,62.485 c2.929,2.929,6.768,4.393,10.606,4.393s7.678-1.464,10.607-4.393l62.483-62.482C304.281,168.352,304.281,158.854,298.423,152.996z"
                ></path>
              </g>
            </svg>
          </div>
        </div>
        {/* Main Heading */}
        <div className="text-7xl flex justify-center font-bold pb-8 text-gradient bg-gradient-to-r from-orange-700 to-red-300 bg-clip-text text-transparent">
          Professional AI Headshots in minutes.
        </div>
        <div className="text-center justify-center items-center flex">
          <p className="text-2xl md:text-2xl md:px-44 font-md tracking-wider max-w-6xl">
            Elevate your online presence with HD headshots generated by our AI.
            Ideal for social profiles, resumes, and professional portfolios.
          </p>
        </div>
        <div className="flex gap-4 justify-center pt-8">
          <Link href="/login">
            <button
              className="flex gap-3 items-center text-center bg-orange-700 hover:bg-orange-800 font-medium text-white px-6 py-2 rounded-lg text-lg 
              transition transform motion-reduce:transition-none motion-reduce:hover:transform-none"
            >
              Get Your Headshots
              {<FaPaintBrush />}
            </button>
          </Link>
        </div>
        <div className="pt-10">
          <Showcase />
        </div>
      </div>
    </section>
  );
};

export default FirstSection;
